// <auto-generated />
using System;
using BookBase.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookBase.Infrastructure.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    partial class BooksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookbase")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookBase.Domain.Models.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Pseudonym")
                        .HasColumnType("text")
                        .HasColumnName("pseudonym");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("Pseudonym")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_pseudonym");

                    b.ToTable("authors", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookCoverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_book_covers");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ix_book_covers_type");

                    b.ToTable("book_covers", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BookCoverId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_cover_id");

                    b.Property<Guid>("BookTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_type_id");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_books_author_id");

                    b.HasIndex("BookCoverId")
                        .HasDatabaseName("ix_books_book_cover_id");

                    b.HasIndex("BookTypeId")
                        .HasDatabaseName("ix_books_book_type_id");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("ix_books_publisher_id");

                    b.HasIndex("Title", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_books_title_author_id");

                    b.ToTable("books", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookGenreEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("BookId", "GenreId")
                        .HasName("pk_book_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_book_genres_genre_id");

                    b.ToTable("book_genres", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_book_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_book_types_name");

                    b.ToTable("book_types", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.ToTable("genres", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.PublisherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_publishers_name");

                    b.ToTable("publishers", "bookbase");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookEntity", b =>
                {
                    b.HasOne("BookBase.Domain.Models.Entities.AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_authors_author_id");

                    b.HasOne("BookBase.Domain.Models.Entities.BookCoverEntity", "BookCover")
                        .WithMany("Books")
                        .HasForeignKey("BookCoverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_books_book_covers_book_cover_id");

                    b.HasOne("BookBase.Domain.Models.Entities.BookTypeEntity", "BookType")
                        .WithMany("Books")
                        .HasForeignKey("BookTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_books_book_types_book_type_id");

                    b.HasOne("BookBase.Domain.Models.Entities.PublisherEntity", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_publishers_publisher_id");

                    b.Navigation("Author");

                    b.Navigation("BookCover");

                    b.Navigation("BookType");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookGenreEntity", b =>
                {
                    b.HasOne("BookBase.Domain.Models.Entities.BookEntity", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_genres_books_book_id");

                    b.HasOne("BookBase.Domain.Models.Entities.GenreEntity", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_genres_genres_genre_id");

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookCoverEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookEntity", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.BookTypeEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.GenreEntity", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("BookBase.Domain.Models.Entities.PublisherEntity", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
